### ISSUE TITLE
Should 'type' have a trailing underscore?

### ISSUE THREAD

**Issue by NathanWailes** [cache-rules/email_hunter_python#2]
In this example...:
`client.search('google.com', type='personal')`

...which can be seen at these links...:
https://pypi.python.org/pypi/email_hunter_python/1.0.1
https://github.com/cache-rules/email_hunter_python/

You'll notice that 'type' doesn't have a trailing underscore.

However when I tried using the code like that, I got an error saying that the specified keyword argument didn't exist. I looked at the code for 'search' and [it looks like the actual keyword argument has a trailing underscore](https://github.com/cache-rules/email_hunter_python/blob/master/email_hunter/email_hunter_client.py#L19).

**Comment by cache-rules** [comment]
You're correct. I just fixed the documentation to have the proper kwarg name. Thanks for pointing this out!
